feat: implementa tela about us do projeto
Kal-il/ES-2023_2-Adoteme pull request #101
Opened 2023-11-16 19:28 UTC by tgofsaints

2023-11-17 12:42 UTC, ana-flav requested changes

2023-11-17 12:42 UTC, ana-flav commented on src/view/pages/AboutUs.php
> +<header>
thiago em vez de escrever o header no arquivo, peço que substitua ele e coloque isso   `<?php include $_SERVER['DOCUMENT_ROOT'] . "/src/view/partials/Header.php" ?>` no lugar

2023-11-17 16:46 UTC, tgofsaints commented
Realizada a implementação do partial referido.

2023-11-18 12:31 UTC, ana-flav approved these changes
obrigada thiagooooo

2023-11-18 23:25 UTC, merged